# Generated by Django 5.2.6 on 2025-09-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='transcoded_playlist',
            field=models.CharField(blank=True, help_text="Path or MinIO key for this audio track's HLS playlist (audio_XX_playlist.m3u8)", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='master_playlist',
            field=models.CharField(blank=True, help_text='Path or MinIO key for master.m3u8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the video transcoding process', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='transcoded_video',
            field=models.CharField(blank=True, help_text='Local path or reference folder of transcoded video and audio files', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcoding_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
