# Generated by Django 5.2.6 on 2025-09-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_audiotrack_transcoded_playlist_video_master_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='is_user_uploaded',
            field=models.BooleanField(default=False, help_text='True if this audio was uploaded by user, False if extracted from video.'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='audio_file',
            field=models.FileField(blank=True, help_text='User-uploaded audio file (mp3, aac, etc.)', null=True, upload_to='audio_tracks/'),
        ),
    ]
