# Generated by Django 5.2.6 on 2025-09-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_audiotrack_is_user_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Audio transcoding progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Transcoding progress percentage (0-100)'),
        ),
    ]
