# Generated by Django 5.2.6 on 2025-09-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_audiotrack_progress_video_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the audio transcoding process', max_length=20),
        ),
    ]
